plugins:
  - serverless-offline
service: rigo

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  check_out:
    handler: handler.checkOut
    events:
      - schedule: cron(15 18 ? * MON-FRI *)
      - http:
          path: /check_out
          method: GET
          cors: true
  check_in:
    handler: handler.checkIn
    events:
      - schedule: cron(45 08 ? * MON-FRI *)
      - http:
          path: /check_in
          method: GET
          cors: true
